#!/usr/bin/env bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# foot server
foot --server --log-no-syslog --log-level=warning &

# ShadowSocks
#sslocal -c /etc/shadowsocks/config.json -d & 

# battery notification (for laptop)
#$scripts/default/battery_notif &

# screen locking when idle
$scripts/default/idle_handler &

# other
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
